### ISSUE TITLE
[Segunda Entrega] Mover jugador

### ISSUE THREAD

**Issue by M-Picco** [BraianVicente/7507-TP2-minecraft#47]
1. En [Tablero::moverJugador](https://github.com/BraianVicente/7507-TP2-minecraft/blob/v1.1/src/fiuba/algo3/minecraft/modelo/tablero/Tablero.java#L132) están preguntando el X e Y de cada posición. Traten de realizar operaciones en base a los objetos que tienen. Por ej: `posFinal.esContigua(posInicial)` o `mapa.eliminarElemento(posInicial)`
3. [Buscar la posición del Jugador](https://github.com/BraianVicente/7507-TP2-minecraft/blob/v1.1/src/fiuba/algo3/minecraft/modelo/tablero/Tablero.java#L118) es una responsabilidad de Tablero? No tendría sentido que el Jugador conozca su propia Posición?
4. La posición nueva del jugador recibida por parámetro puede ser cualquiera, sin embargo siempre se chequea que sea contigua a la inicial. ¿Tiene sentido entonces pasar la posición final si siempre debería ser contigüa?
5. Vinculado al punto anterior: se podría modelar la dirección del movimiento
6. La clase tiene mucha lógica de inicialización que no le corresponde. Definan cual es el conjunto de operaciones de un tablero y dejen la lógica de inicialización a una clase superior que lo consuma, como sería Juego
7. Está modelada la Posición pero se está usando muy poco. [Mapa](https://github.com/BraianVicente/7507-TP2-minecraft/blob/v1.1/src/fiuba/algo3/minecraft/modelo/mapa/Mapa.java)
 prácticamente no hace uso de esta. Traten de usar "coordenadas x e y" lo menos posible y usar más "una posición"

**Comment by BraianVicente** [comment]
@M-Picco con respecto al punto 5 surgen algunas dudas.
Si se delega a una clase superior entonces se debería crear un constructor de un Tablero que reciba un mapa como parámetro. La clase superior debería inicializar el mapa y para esto debe saber como recorrerlo por lo cual esa nueva clase superior debe en cierta medida saber de la implementacion del mismo. ¿Esto no estaría también violando el contrato del mapa?

Respecto al punto 3, una posible solución es que el tablero reciba la ubicacion a la cual se quiere mover el jugador, y este le pida al mapa que mueva el jugador de posición, y el mapa se encargue de realizarlo haciendo los chequeos que sean necesarios, ¿esta solución es adecuada?

**Comment by M-Picco** [comment]
5) Para iniciar el mapa no es necesario que la clase que lo consuma sepa cómo se recorre. Solo sabe que Mapa responde a un contrato con un conjunto definido de operaciones. Por ejemplo:

```
interface Mapa {
        void agregarElemento(Posicion posicion, Posicionable posicionable);
        Posicionable removerElemento(Posicion posicion);
}
```

La clase que consume sabe que un Mapa representa una grilla de NxM y que puede agregar o sacar elementos de cada posición. Por atrás no sabe cómo se implementa el esquema de posiciones.

3) Por lo que entiendo que vienen trabajando el Mapa solo representa la grilla. Mover un objeto sería añadirle más responsabilidades de las que debiera tener. El Tablero y Jugador claramente van a tener que interactuar de alguna manera para el movimiento. Un tip: por más que resulte muy abstracto, tiene total sentido que haya una entidad o clase que represente un Movimiento
